# Etapa 1: Construcción
FROM node:22-alpine AS build
WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias (solo producción)
RUN npm install --production

# Copiar el resto del proyecto
COPY . .

# Etapa 2: Ejecución
FROM node:22-alpine
WORKDIR /app

# Copiar archivos construidos desde la etapa anterior
COPY --from=build /app /app

# Copiar .env (si existe en la raíz del servicio)
COPY .env .env

ENV NODE_ENV=production
ENV PORT=8087

EXPOSE 8087

CMD ["node", "src/index.js"]
