# Etapa 1: Construcción (instalación de dependencias)
FROM node:22-alpine AS build

# Establecer directorio de trabajo
WORKDIR /app

# Copiar los archivos del proyecto
COPY package*.json ./

# Instalar dependencias (solo producción)
RUN npm install --production

# Copiar todo el código fuente
COPY . .

# Etapa 2: Ejecución
FROM node:22-alpine

WORKDIR /app

# Copiar archivos desde la etapa anterior
COPY --from=build /app /app

# Copiar el .env del servicio
COPY .env .env

# Variables de entorno por defecto
ENV NODE_ENV=production
ENV PORT=8087

# Exponer puerto del microservicio
EXPOSE 8087

# Comando de inicio
CMD ["node", "src/index.js"]
