# Etapa 1: Construcción
FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./

# Instalamos todo (incluyendo dev) para asegurar que se construya bien
RUN npm install

COPY . .

# Etapa 2: Ejecución (Imagen limpia)
FROM node:22-alpine

WORKDIR /app

# Copiamos solo los node_modules y el código desde la etapa anterior
COPY --from=build /app /app

# --- AQUÍ ESTABA EL ERROR ---
# BORRAMOS LA LÍNEA: COPY .env .env
# Confiamos 100% en las variables que vienen del docker-compose.yml

ENV NODE_ENV=production
ENV PORT=8089

EXPOSE 8089

CMD ["node", "index.js"]